fix: send task output message as string
The message argument should now be passed as a string instead of a dict,
which caused: `AttributeError: 'dict' object has no attribute 'encode'`

Signed-off-by: Edward Ly <contact@edward.ly>